version: "2"
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
checks:
  method-lines:
    enabled: false
  file-lines:
    enabled: false
  complex-logic:
    enabled: false
  method-complexity:
    config:
      threshold: 9
exclude_paths:
- test/
- docs/
- assets/
- compose/
- scripts/
- tutorials/
- packages/ringpop/
- packages/**/test/
- packages/skyring/lib/server/api/validators/timer.js 
