FROM  mhart/alpine-node:7
COPY . /opt/skyring
WORKDIR /opt/skyring
RUN apk update && \ 
    apk upgrade && \
    apk add python make g++

ENV NODE_ENV=development
RUN npm --python=python2 --registry=http://registry.npmjs.org install
WORKDIR /opt
RUN tar --exclude="*.tar.gz" --exclude="*.tgz" -zcf skyring.tgz -C /opt skyring
WORKDIR /opt/skyring
