sudo: required
services:
  - docker

script: npm test
language: node_js
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libzmq3-dev
  - docker run -d -p 4222:4222 nats:latest
git:
  depth: 3
node_js:
  - "6"
  - "7"
  - "8"
addons:
  code_climate:
    repo_token: 248135f96061f77d2e5f78526432fd096785d2914d8f5a73a04c061000939d5d
matrix:
  include:
    - node_js: 6
      env: ZMQ_BIND=1
      sudo: required
      dist: trusty
      services:
        - docker
    - node_js: 7
      env: ZMQ_BIND=1
      sudo: required
      dist: trusty
      services:
        - docker
    - node_js: 8
      env: ZMQ_BIND=1
      sudo: required
      dist: trusty
      services:
        - docker
