version: '2.4'
services:
  nats-a:
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222

  scylla-1:
    ports:
      - 9160:9160
      - 9042:9042

  scylla-2:
    ports:
      - 9043:9042

  scylla-3:
    ports:
      - 9044:9042

  nginx:
    image: 'nginx:latest'
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - skyring
    depends_on:
      - node-1
      - node-2
      - node-3
      - node-4
      - node-5

  node-1:
    build:
      context: ../
    hostname: node-1
    environment:
      channel__host: 'node-1'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      seeds: 'node-1:3455,node-2:3456'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  node-2:
    build:
      context: ../
    hostname: node-2
    environment:
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-2'
      channel__port: 3456
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  node-3:
    build:
      context: ../
    hostname: node-3
    environment:
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-3'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - node-1
      - node-2

  node-4:
    build:
      context: ../
    hostname: node-4
    environment:
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-4'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - node-1
      - node-2

  node-5:
    build:
      context: ../
    hostname: node-5
    environment:
      seeds: 'node-1:3455,node-2:3456'
      nats__hosts: 'nats-a:4222,nats-b:4222,nats-c:4222'
      channel__host: 'node-5'
      storage__backend: 'leveldown'
      storage__path: /var/data/skyring
      NODE_ENV: test
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - node-1
      - node-2
      - node-3
      - node-4

networks:
  skyring:
    driver: bridge
