apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}-seed
  labels:
    app: {{ .Values.nameOverride }}-seed
    chart: {{ template "skyring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: port-one
      port: 3455
      targetPort: 3455
    - name: port-two
      port: 3456
      targetPort: 3456
    - name: port-three
      port: 3000
      targetPort: 3000
  selector:
    app: {{ .Values.nameOverride }}-seed
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
    chart: {{ template "skyring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: port-one
      port: 3455
      targetPort: 3455
    - name: port-two
      port: 3456
      targetPort: 3456
    - name: port-three
      port: 3000
      targetPort: 3000
  selector:
    app: {{ .Values.nameOverride }}
    release: {{ .Release.Name }}