apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ .Values.nameOverride }}-seed
  labels:
    app: {{ .Values.nameOverride }}-seed
    chart: {{ template "skyring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.SeedReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}-seed
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride }}-seed
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: nats-pause
        image: yauritux/busybox-curl
        command:
        - curl
        - "http://{{ .Release.Name }}-nats-client:4222/monitoring"
      {{- if .Values.persistent.enabled }}
      - name: mongo-pause
        image: yauritux/busybox-curl
        command:
        - curl
        - "http://{{ .Release.Name }}-mongodb-headless:9216/metrics"
      {{- end }}
      containers:
        - name: {{ .Values.nameOverride }}-seed
          image: {{ .Values.image.repository }}:{{ if not .Values.persistent.enabled }}{{ .Values.image.tag }}{{ end }}{{ if .Values.persistent.enabled }}{{ .Values.image.persistent_tag }}{{ end}}
          imagePullPolicy: Always
          ports:
            - name: port-one
              containerPort: 3455
            - name: port-two
              containerPort: 3456
            - name: port-three
              containerPort: 3000
          env:
            {{- if eq .Values.debug true }}
            - name: DEBUG
              value: "*"
            {{- end }}
            - name: channel__host
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: nats__hosts
              value: '{{ .Release.Name }}-nats-client:4222'
            - name: seeds
              value: '{{ .Values.nameOverride }}-seed:3455'
            {{- if not .Values.persistent.enabled }}
            - name: storage__backend
              value: 'leveldown'
            - name: storage__path
              value: /var/data/skyring
            {{- end }}
            {{- if .Values.persistent.enabled }}
            - name: storage__backend
              value: 'mongodown'
            - name: storage__path
              value: 'mongodb://{{ .Release.Name }}-mongodb:27017/skyring'
            - name: storage__collection
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
    chart: {{ template "skyring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.WorkerReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: nats-pause
        image: yauritux/busybox-curl
        command:
        - curl
        - "http://{{ .Release.Name }}-nats-client:4222/monitoring"
      {{- if .Values.persistent.enabled }}
      - name: mongo-pause
        image: yauritux/busybox-curl
        command:
        - curl
        - "http://{{ .Release.Name }}-mongodb-headless:9216/metrics"
      {{- end }}
      containers:
        - name: {{ .Values.nameOverride }}
          image: {{ .Values.image.repository }}:{{ if not .Values.persistent.enabled }}{{ .Values.image.tag }}{{ end }}{{ if .Values.persistent.enabled }}{{ .Values.image.persistent_tag }}{{ end}}
          imagePullPolicy: Always
          ports:
            - name: port-one
              containerPort: 3455
            - name: port-two
              containerPort: 3456
            - name: port-three
              containerPort: 3000
          env:
            {{- if eq .Values.debug true }}
            - name: DEBUG
              value: "*"
            {{- end}}
            - name: channel__host
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: nats__hosts
              value: '{{ .Release.Name }}-nats-client:4222'
            - name: seeds
              value: '{{ .Values.nameOverride}}-seed:3455'
            {{- if not .Values.persistent.enabled }}
            - name: storage__backend
              value: 'leveldown'
            - name: storage__path
              value: /var/data/skyring
            {{- end }}
            {{- if .Values.persistent.enabled }}
            - name: storage__backend
              value: 'mongodown'
            - name: storage__path
              value: 'mongodb://{{ .Release.Name }}-mongodb:27017/skyring'
            - name: storage__collection
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
---
