name: Test + Release

on:
  pull_request:
    branches:
      - main

  push:
    branch:
      - main
jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npx pnpm install -r
      - name: Docker Compose up
        run: npm start -- -d
      - name: Test
        run: npm run tap -Rclassic
        env:
          TEST_HOST: localhost
          NODE_ENV: test
          LOG__LEVEL: error

  release:
    name: release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npx pnpm install -r

      - name: Publish
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          GIT_AUTHOR_NAME: 'Dependant Bot'
          GIT_AUTHOR_EMAIL: 'release-bot@codedependant.net'
          GIT_COMMITTER_NAME: 'Dependant Bot'
          GIT_COMMITTER_EMAIL: 'release-bot@codedependant.net'
