name: Test + Release

on:
  pull_request:
    branches:
      - master

  push:
    branch:
      - master
jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npx pnpm install -r
      - name: Docker Compose up
        run: npm start -- -d
      - name: Test
        run: npm run tap
        env:
          TEST_HOST: localhost
          NODE_ENV: test
